### ISSUE TITLE
Problems: Not Data

### ISSUE THREAD

**Issue by NogGo** [NogGo/sat-all#7]
***
**Priority**: blocking
***
1. Обновить проект sat-all
2. Запустить
3. Перейти по урлу, /onexbet
4. Проблема работы с ws:
  * Не приходят данные по (левому) урл (?connect...)
  * Не приходят данные по урл реконнекту
  * не приходят данные по урл, в JS
Урл везде это wss, кроме ссылки получение json с токеном см. код в sat-all
5. Необходим мозговой штурм))

**Comment by ArtemMe** [comment]
done
